help:
  @just --list

# Build, increment patch number and publish
patch: build
  yarn version --patch
  @just upload

# Publish to npm
upload:
  cd dist && npm publish

# Build package into dist/, copying relevant files
build: 
  rm -dr dist || :
  yarn run build
  @just copy

# Copy package.json, tsconfig.json and README.md to dist/
copy:
  cp package.json dist
  cp tsconfig.json dist
  cp README.md dist

# Install a package as both --dev and --peer (pseudo-analogous to python extras)
extra PACKAGE:
  yarn add --peer {{PACKAGE}} && yarn add --dev {{PACKAGE}}

# Install react stuff
install-react:
  yarn add --dev eslint-plugin-react-hooks
  yarn add react react-dom --dev @types/react @types/react-dom