set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

dev PORT="5000":
  yarn dev --host --port {{PORT}}

build:
  yarn run build

preview:
  yarn preview --host

init:
  yarn run build
  npx cap add android
  npx cap open android

open:
  npx cap open android