help:
  @just --list

# Link the Moveread images
images DEST='.':
  ln -s $CIT_BASE/resources/images {{invocation_directory()}}/{{DEST}}

# Copy the Moveread images
images-cp DEST='.':
  cp -r $CIT_BASE/resources/images {{invocation_directory()}}/{{DEST}}

# Add a .venv, requirements.txt, .vscode with config. Installs requirements.txt if existent
python HERE='.':
  mkdir {{invocation_directory()}}/{{HERE}}/.vscode || :
  cd {{invocation_directory()}}/{{HERE}}/.vscode && \
    [ ! -f settings.json ] && echo "{}" > settings.json || : && \
    jq '. + {"python.defaultInterpreterPath": ".venv/bin/python"}' settings.json > temp.json && mv temp.json settings.json && \
    jq '. + {"python.analysis.typeCheckingMode": "standard"}' settings.json > temp.json && mv temp.json settings.json

  cp -a $CIT_BASE/resources/python/settings/. {{invocation_directory()}}/{{HERE}}/.vscode
  echo "" >> {{invocation_directory()}}/{{HERE}}/Justfile
  cat $CIT_BASE/resources/python/Justfile >> {{invocation_directory()}}/{{HERE}}/Justfile
  cat $CIT_BASE/resources/python/.gitignore >> {{invocation_directory()}}/{{HERE}}/.gitignore

  cd {{invocation_directory()}}/{{HERE}} && \
  if ! test -f requirements.txt; then \
    echo "build" >> requirements.txt && \
    echo "twine" >> requirements.txt && \
    echo "ipykernel" >> requirements.txt && \
    python3.11 -m venv .venv && \
    .venv/bin/python -m pip install --upgrade pip && \
    .venv/bin/python -m pip install -r requirements.txt; \
  fi 
  
  
