TEMPLATES := "$CIT_BASE" + "/resources/templates"

help:
  @just --list

# Scaffold a python package
python NAME DESCRIPTION='package_description':
  cp -r {{TEMPLATES}}/python-pkg {{invocation_directory()}}/{{NAME}}
  cd {{invocation_directory()}}/{{NAME}} && \
  sed -i 's/<NAME>/{{file_name(NAME)}}/g; s/<DESCRIPTION>/{{DESCRIPTION}}/g' pyproject.toml && \
  sed -i 's/<NAME>/{{titlecase(file_name(NAME))}}/g; s/<DESCRIPTION>/{{DESCRIPTION}}/g' README.md && \
  sed -i 's/<NAME>/{{titlecase(file_name(NAME))}}/g; s/<DESCRIPTION>/{{DESCRIPTION}}/g' src/NAME/__init__.py && \
  mv src/NAME src/{{snakecase(file_name(NAME))}}

# Scaffold a typescript node package
typescript NAME DESCRIPTION='package_description':
  cp -r {{TEMPLATES}}/ts-pkg {{invocation_directory()}}/{{NAME}}
  cd {{invocation_directory()}}/{{NAME}} && \
  sed -i 's/<NAME>/{{file_name(NAME)}}/g; s/<DESCRIPTION>/{{DESCRIPTION}}/g' package.json && \
  sed -i 's/<NAME>/{{titlecase(file_name(NAME))}}/g; s/<DESCRIPTION>/{{DESCRIPTION}}/g' README.md && \
  yarn

# Scaffold a react x vite app
react NAME='app_name' DESCRIPTION='app_description':
  cp -r {{TEMPLATES}}/react-vite {{invocation_directory()}}/{{NAME}}
  cd {{invocation_directory()}}/{{NAME}} && \
  sed -i 's/<NAME>/{{file_name(NAME)}}/g; s/<DESCRIPTION>/{{DESCRIPTION}}/g' package.json && \
  sed -i 's/<NAME>/{{titlecase(file_name(NAME))}}/g; s/<DESCRIPTION>/{{DESCRIPTION}}/g' index.html && \
  yarn