WORKSPACES := `echo $CIT_BASE` + "/resources/workspaces"

test:
  echo {{WORKSPACES}}

help:
  @just --list --justfile open.just

# Open cit
cit:
  @ echo Opening $CIT_BASE
  code $CIT_BASE

moveread-ocr:
  code /home/m4rs/mr-github/rnd/moveread-ocr/

haskellian:
  code /home/m4rs/github/lib/haskellian

haskellian-js:
  code /home/m4rs/github/lib/haskellian-js

queues:
  code /home/m4rs/mr-github/lib/python/tools/python-q/

core:
  code /home/m4rs/mr-github/rnd/data/python-core

pipelines:
  code /home/m4rs/mr-github/rnd/data/moveread-pipelines

storage:
  code /home/m4rs/github/python-storage

dfy:
  code /home/m4rs/mr-github/modes/moveread-dfy

lite:
  code /home/m4rs/mr-github/modes/lite-mode

chess:
  code /home/m4rs/mr-github/lib/chess/

landing:
  code /home/m4rs/mr-github/modes/moveread-landing