help:
  @just --list --justfile open.just

# Open cit
cit:
  @ echo Opening $CIT_BASE
  code $CIT_BASE

moveread-ocr:
  code /home/m4rs/mr-github/rnd/ml/moveread-ocr/

haskellian:
  code /home/m4rs/mr-github/lib/python/tools/haskellian/

lite-mode:
  code /home/m4rs/mr-github/modes/lite/lite-mode/