help:
  @just --list

# Run the OCR model tfserving on localhost:8501
ocr:
  docker run -d -p 8501:8501 --name ocr moveread/tfx-ocr:0.0.1

# Kill the OCR docker container
ocr-kill:
  docker rm -f ocr

predict-fastapi: ocr-kill ocr
  cd /home/m4rs/mr-github/rnd/ops/composed-predict/ && just server dev

[no-cd]
moveread-api PATH:
  /home/m4rs/mr-github/rnd/data/python-core/.venv/bin/moveread-api --base-path {{PATH}}